### ISSUE TITLE
"Show treemap" option does not persist after restart

### ISSUE THREAD

**Issue by Kadilov** [jeromerobert/k4dirstat#30]
"Show treemap" option is always activated after restart, even if I unchecked it before closing the window.
Version 3.1.4 on openSUSE Leap 15.1.

**Comment by jeromerobert** [comment]
Indeed it's saved here https://github.com/jeromerobert/k4dirstat/blob/fd99802/src/k4dirstat.cpp#L396 but this function seems to be never called.
