### ISSUE TITLE
Display free space on treemap

### ISSUE THREAD

**Issue by bondden** [jeromerobert/k4dirstat#31]
Is it possible to display free space (as minimum for a selected disk) on the treemap widget?

**Comment by jeromerobert** [comment]
[`statvfs`](https://linux.die.net/man/2/statvfs) seems to work for any file so it's possible to display it even for a folder which is not the root of a filesystem. I could show it in the *Subtree Percentage* or *Percentage* columns as they are not used for the root node. I could also show it in a tooltip.

**Comment by jeromerobert** [comment]
The *Subtree Percentage* is used to show the number of remaining scan jobs so I'm using the *Percentage*:
![k4dirstat-sc](https://user-images.githubusercontent.com/160365/85224834-58573800-b3cd-11ea-9b87-f4009303abf0.png)
I currently only show it on the root node.

**Comment by jeromerobert** [comment]
Well it's not very intuitive. I'll try to move it to the status bar or to a tool tip.
