### ISSUE TITLE
Opensuse 15.2 immediate crash

### ISSUE THREAD

**Issue by tazio** [jeromerobert/k4dirstat#32]
It happens every time I click on "Open"

[k4dirstat-20200705-134835.kcrash.txt](https://github.com/jeromerobert/k4dirstat/files/4874862/k4dirstat-20200705-134835.kcrash.txt)

**Comment by jeromerobert** [comment]
Which version of k4dirstat is it ?

**Comment by tazio** [comment]
3.2.0

**Comment by jeromerobert** [comment]
So this is #28 and it's fixed in 3.2.1.
