### ISSUE TITLE
k4dirstat crashes after OpenSuSE Leap 15.2 install

### ISSUE THREAD

**Issue by gjjohnson** [jeromerobert/k4dirstat#33]
See attached file.
Please contact me if you need additional information to debug this issue.

[k4dirstat-20200707-191144.kcrash.txt](https://github.com/jeromerobert/k4dirstat/files/4888069/k4dirstat-20200707-191144.kcrash.txt)

**Comment by jeromerobert** [comment]
Duplicate #28 #32

**Comment by gjjohnson** [comment]
I have opened a request to OpenSuSE to add the current k4dirstat (3.2.1) to their maintenance release on OpenSuSE Leap 15.

Bug 1173905 - When opening k4dirstat from applications menu and clicking on "Open...", an empty file picker dialog window appears and k4dirstat crashes.

Thanks for your support!
