### ISSUE TITLE
K4dirstat  crash straight after launching it at archlinux

### ISSUE THREAD

**Issue by tyler820201** [jeromerobert/k4dirstat#35]
Application: k4dirstat (5a86d13)

Qt Version: 5.15.0
Frameworks Version: 5.73.0
Operating System: Linux 5.7.12-arch1-1 x86_64
Windowing system: X11
Distribution: Arch Linux

-- Information about the crash:
<I am using archlinux installed on microSD card 128GB. However i have 2TB SSD (Samsung 860EVO) also installed with Debian and win10 system as dualboot. On debian (Kubuntu 18.04 LTS) i have no issue with K4DirStat.>

The crash can be reproduced every time.

-- Backtrace:
Application: k4dirstat (k4dirstat), signal: Segmentation fault

[KCrash Handler]
#4  0x000055fe311fa085 in KDirSortFilterProxyModel::lessThan(QModelIndex const&, QModelIndex const&) const ()
#5  0x00007ff7911fe338 in ?? () from /usr/lib/libQt5Core.so.5
#6  0x00007ff791201863 in ?? () from /usr/lib/libQt5Core.so.5
#7  0x00007ff7911f2a80 in ?? () from /usr/lib/libQt5Core.so.5
#8  0x00007ff7911f79ef in ?? () from /usr/lib/libQt5Core.so.5
#9  0x00007ff7911fb836 in ?? () from /usr/lib/libQt5Core.so.5
#10 0x00007ff79125ca60 in ?? () from /usr/lib/libQt5Core.so.5
#11 0x00007ff7911befcf in QAbstractItemModel::rowsInserted(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () from /usr/lib/libQt5Core.so.5
#12 0x00007ff7911c7851 in QAbstractItemModel::endInsertRows() () from /usr/lib/libQt5Core.so.5
#13 0x00007ff7927e51c1 in ?? () from /usr/lib/libKF5KIOWidgets.so.5
#14 0x00007ff79125ca26 in ?? () from /usr/lib/libQt5Core.so.5
#15 0x00007ff7925d885b in KCoreDirLister::itemsAdded(QUrl const&, KFileItemList const&) () from /usr/lib/libKF5KIOCore.so.5
#16 0x00007ff7925dfe45 in ?? () from /usr/lib/libKF5KIOCore.so.5
#17 0x00007ff7925f18c0 in ?? () from /usr/lib/libKF5KIOCore.so.5
#18 0x00007ff79125ca26 in ?? () from /usr/lib/libQt5Core.so.5
#19 0x00007ff7925a0eb5 in KIO::ListJob::entries(KIO::Job*, QList<KIO::UDSEntry> const&) () from /usr/lib/libKF5KIOCore.so.5
#20 0x00007ff79125ca26 in ?? () from /usr/lib/libQt5Core.so.5
#21 0x00007ff79258e106 in KIO::SlaveInterface::listEntries(QList<KIO::UDSEntry> const&) () from /usr/lib/libKF5KIOCore.so.5
#22 0x00007ff79258fecb in KIO::SlaveInterface::dispatch(int, QByteArray const&) () from /usr/lib/libKF5KIOCore.so.5
#23 0x00007ff79258e66a in KIO::SlaveInterface::dispatch() () from /usr/lib/libKF5KIOCore.so.5
#24 0x00007ff79259216b in KIO::Slave::gotInput() () from /usr/lib/libKF5KIOCore.so.5
#25 0x00007ff79125ca26 in ?? () from /usr/lib/libQt5Core.so.5
#26 0x00007ff7912521d2 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#27 0x00007ff791cf3702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#28 0x00007ff7912257ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#29 0x00007ff7912282a3 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#30 0x00007ff79127ecf4 in ?? () from /usr/lib/libQt5Core.so.5
#31 0x00007ff78fa9f43c in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#32 0x00007ff78faed1d9 in ?? () from /usr/lib/libglib-2.0.so.0
#33 0x00007ff78fa9e221 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#34 0x00007ff79127e331 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#35 0x00007ff79122413c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#36 0x00007ff791ef6baa in QDialog::exec() () from /usr/lib/libQt5Widgets.so.5
#37 0x00007ff791ef6ae6 in QDialog::exec() () from /usr/lib/libQt5Widgets.so.5
#38 0x00007ff791f0a2a9 in QFileDialog::getExistingDirectoryUrl(QWidget*, QString const&, QUrl const&, QFlags<QFileDialog::Option>, QStringList const&) () from /usr/lib/libQt5Widgets.so.5
#39 0x000055fe311ecbe7 in k4dirstat::fileAskOpenDir() ()
#40 0x00007ff79125ca60 in ?? () from /usr/lib/libQt5Core.so.5
#41 0x00007ff791cecf23 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#42 0x00007ff791cef805 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#43 0x00007ff791de6f72 in ?? () from /usr/lib/libQt5Widgets.so.5
#44 0x00007ff791de7093 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#45 0x00007ff791edba8b in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#46 0x00007ff791d34c7e in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#47 0x00007ff791cf3702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#48 0x00007ff791cfa977 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#49 0x00007ff7912257ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#50 0x00007ff791cf985e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#51 0x00007ff791d4d3b2 in ?? () from /usr/lib/libQt5Widgets.so.5
#52 0x00007ff791d5078f in ?? () from /usr/lib/libQt5Widgets.so.5
#53 0x00007ff791cf3702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#54 0x00007ff7912257ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#55 0x00007ff79160037c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#56 0x00007ff7915d5b4c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#57 0x00007ff78d047c8c in ?? () from /usr/lib/libQt5XcbQpa.so.5
#58 0x00007ff78fa9f43c in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#59 0x00007ff78faed1d9 in ?? () from /usr/lib/libglib-2.0.so.0
#60 0x00007ff78fa9e221 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#61 0x00007ff79127e331 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#62 0x00007ff79122413c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#63 0x00007ff79122c5c4 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#64 0x000055fe311e56ef in main ()
[Inferior 1 (process 1181) detached]

**Comment by jeromerobert** [comment]
Which version of k4dirstat is it ? (There is no 5a86d13 in the k4dirstat repository).

**Comment by tyler820201** [comment]
k4dirstat (3.2.0-1) from AUR

**Comment by jeromerobert** [comment]
This is fixed in 3.2.1. See #28

**Comment by tyler820201** [comment]
Thanks
