### ISSUE TITLE
Can I disable autostart?

### ISSUE THREAD

**Issue by canis76** [jeromerobert/k4dirstat#52]
I have no idea why, but this wonderful software auto-starts, and I can't figure out how to stop it.  This has been the behavior since the initial install.  It's probably responding to something I've done to my kubuntu.  I don't know how to turn off something I don't remember turning on indirectly.  I love the speed, and familiar feel.  Please keep up the good work.

**Comment by jeromerobert** [comment]
I think it's not something that k4dirstat is responsible for. You should have a look to https://userbase.kde.org/System_Settings/Desktop_Session

**Comment by canis76** [comment]
Welp, when you put it that way I can only apologize for wasting your time.  I did Change those.  I didn't realize that the program hangs around somewhere after I close it.  I have shortcuts for everything.  I only have the session save thing on to be very lazy.  Thank you.
